version: '3.1'
services:
  redis:
    image: redis:7-alpine
    restart: on-failure
    environment:
       SECRET_KEY: /run/secrets/redis-secret
    ports:
      - "6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass SECRET_KEY
    networks:
      - my-network
    secrets:
      - redis-secret
  client:
    build: ./client
    container_name: promark-portal-c
    restart: on-failure
    ports:
      - "80:3000"
    volumes:
      - ./client:/app
      - ./app/node_modules
    networks:
      - my-network
  flask_server:
    build: ./server
    container_name: flask_server
    restart: on-failure
    environment:
       SECRET_KEY: /run/secrets/redis-secret
    ports:
      - "5000:5000"
    volumes:
      - ./server:/code
    networks:
      - my-network
    secrets:
      - redis-secret

networks:
  my-network:
    driver: bridge

secrets:
  redis-secret:
    file: ./redispass.txt  
